login:
    path: /login
    defaults: { _controller: 'App\Controller\DefaultController::login' }

logout:
    path: /logout
    defaults: { _controller: 'App\Controller\DefaultController:logout' }


reset2factor:
    path: /reset2factor
    defaults: { _controller: 'App\Controller\DefaultController:reset2factor' }

catchall:
    path: /{req}
    defaults: { _controller: 'App\Controller\DefaultController:catchall' }
    requirements:
        req: ".*"
